.TH SAMDUMP2 1 "October 2006" "Version 1.0.0"

.SH NAME
.B samdump2
dumps Windows 2k/NT/XP password hashes.
.SH SYNOPSIS
samdump2 <sam hive> <key file>
.SH EXAMPLE
samdump2 /mnt/ntfs/WINDOWS/system32/config/sam out
.SH AUTHOR
This manual page was written by Adam Cecile <gandalf@le-vert.net> for the Debian system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
.SH SEE ALSO
.br
.B bkhive(1)
.br
.B ophcrack(1)
